### ISSUE TITLE
Porting Flutter

### ISSUE THREAD

**Issue by nuta** [nuta/resea#35]
Flutter is an open-source GUI component developed by Google. It supports iOS, Android, and their own non-Linux operating system called Fuchsia.

## Tasks
- [ ] Learn how Flutter works
- [ ] Port Flutter Engine
- [ ] Implement virtio-gpu

**Comment by nuta** [comment]
Unfortunately, it turned out that Flutter is portable only if the target operating system is already supported.
