### ISSUE TITLE
Porting to Raspberry Pi Pico

### ISSUE THREAD

**Issue by nuta** [nuta/resea#51]
## TODOs

- [ ] Get the board
- [ ] make: Support flashing built image
- [ ] kernel: Write machine-specific code (serial port and timer driver)
- [ ] driver: Implement RP2040-specific peripherals (e.g. RTC)

## References
- [RP2040 Datasheet](https://datasheets.raspberrypi.org/rp2040/rp2040-datasheet.pdf)
